// Code generated by protoc-gen-go. DO NOT EDIT.
// source: page_api.proto

package page_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Templates
type LayoutType int32

const (
	LayoutType_empty    LayoutType = 0
	LayoutType_desktop  LayoutType = 1
	LayoutType_mobile   LayoutType = 2
	LayoutType_adaptive LayoutType = 3
)

var LayoutType_name = map[int32]string{
	0: "empty",
	1: "desktop",
	2: "mobile",
	3: "adaptive",
}

var LayoutType_value = map[string]int32{
	"empty":    0,
	"desktop":  1,
	"mobile":   2,
	"adaptive": 3,
}

func (x LayoutType) String() string {
	return proto.EnumName(LayoutType_name, int32(x))
}

func (LayoutType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{0}
}

type Template struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OfferId              int32    `protobuf:"varint,3,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	LayoutType           int32    `protobuf:"varint,5,opt,name=layout_type,json=layoutType,proto3" json:"layout_type,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Uuid                 string   `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IsMyTarget           bool     `protobuf:"varint,8,opt,name=is_my_target,json=isMyTarget,proto3" json:"is_my_target,omitempty"`
	TransitedUrl         string   `protobuf:"bytes,9,opt,name=transited_url,json=transitedUrl,proto3" json:"transited_url,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Visibility           int32    `protobuf:"varint,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{0}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Template) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *Template) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Template) GetLayoutType() int32 {
	if m != nil {
		return m.LayoutType
	}
	return 0
}

func (m *Template) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Template) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Template) GetIsMyTarget() bool {
	if m != nil {
		return m.IsMyTarget
	}
	return false
}

func (m *Template) GetTransitedUrl() string {
	if m != nil {
		return m.TransitedUrl
	}
	return ""
}

func (m *Template) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Template) GetVisibility() int32 {
	if m != nil {
		return m.Visibility
	}
	return 0
}

type ListTemplatesRequest struct {
	Id                   []int32  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OfferIds             []int32  `protobuf:"varint,4,rep,packed,name=offer_ids,json=offerIds,proto3" json:"offer_ids,omitempty"`
	AffiliateId          int32    `protobuf:"varint,5,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	Limit                int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTemplatesRequest) Reset()         { *m = ListTemplatesRequest{} }
func (m *ListTemplatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListTemplatesRequest) ProtoMessage()    {}
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{1}
}

func (m *ListTemplatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTemplatesRequest.Unmarshal(m, b)
}
func (m *ListTemplatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTemplatesRequest.Marshal(b, m, deterministic)
}
func (m *ListTemplatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTemplatesRequest.Merge(m, src)
}
func (m *ListTemplatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListTemplatesRequest.Size(m)
}
func (m *ListTemplatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTemplatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTemplatesRequest proto.InternalMessageInfo

func (m *ListTemplatesRequest) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ListTemplatesRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ListTemplatesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListTemplatesRequest) GetOfferIds() []int32 {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

func (m *ListTemplatesRequest) GetAffiliateId() int32 {
	if m != nil {
		return m.AffiliateId
	}
	return 0
}

func (m *ListTemplatesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListTemplatesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListTemplatesResponse struct {
	Templates            []*Template `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	TotalCount           int32       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListTemplatesResponse) Reset()         { *m = ListTemplatesResponse{} }
func (m *ListTemplatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListTemplatesResponse) ProtoMessage()    {}
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{2}
}

func (m *ListTemplatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTemplatesResponse.Unmarshal(m, b)
}
func (m *ListTemplatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTemplatesResponse.Marshal(b, m, deterministic)
}
func (m *ListTemplatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTemplatesResponse.Merge(m, src)
}
func (m *ListTemplatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListTemplatesResponse.Size(m)
}
func (m *ListTemplatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTemplatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTemplatesResponse proto.InternalMessageInfo

func (m *ListTemplatesResponse) GetTemplates() []*Template {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *ListTemplatesResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

// Stream
type Stream struct {
	Id                   int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserId               int32              `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OfferId              int32              `protobuf:"varint,4,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Name                 string             `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string             `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	PrelandingOptions    *StreamPageOptions `protobuf:"bytes,7,opt,name=prelanding_options,json=prelandingOptions,proto3" json:"prelanding_options,omitempty"`
	LandingOptions       *StreamPageOptions `protobuf:"bytes,8,opt,name=landing_options,json=landingOptions,proto3" json:"landing_options,omitempty"`
	ThanksOptions        *StreamPageOptions `protobuf:"bytes,9,opt,name=thanks_options,json=thanksOptions,proto3" json:"thanks_options,omitempty"`
	TrafficBackUrl       string             `protobuf:"bytes,10,opt,name=traffic_back_url,json=trafficBackUrl,proto3" json:"traffic_back_url,omitempty"`
	IsMyTarget           bool               `protobuf:"varint,11,opt,name=is_my_target,json=isMyTarget,proto3" json:"is_my_target,omitempty"`
	Sub1                 string             `protobuf:"bytes,12,opt,name=sub1,proto3" json:"sub1,omitempty"`
	Sub2                 string             `protobuf:"bytes,13,opt,name=sub2,proto3" json:"sub2,omitempty"`
	Sub3                 string             `protobuf:"bytes,14,opt,name=sub3,proto3" json:"sub3,omitempty"`
	Sub4                 string             `protobuf:"bytes,15,opt,name=sub4,proto3" json:"sub4,omitempty"`
	Sub5                 string             `protobuf:"bytes,16,opt,name=sub5,proto3" json:"sub5,omitempty"`
	GeoCode              []string           `protobuf:"bytes,17,rep,name=geo_code,json=geoCode,proto3" json:"geo_code,omitempty"`
	Currency             string             `protobuf:"bytes,18,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{3}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Stream) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Stream) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Stream) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Stream) GetPrelandingOptions() *StreamPageOptions {
	if m != nil {
		return m.PrelandingOptions
	}
	return nil
}

func (m *Stream) GetLandingOptions() *StreamPageOptions {
	if m != nil {
		return m.LandingOptions
	}
	return nil
}

func (m *Stream) GetThanksOptions() *StreamPageOptions {
	if m != nil {
		return m.ThanksOptions
	}
	return nil
}

func (m *Stream) GetTrafficBackUrl() string {
	if m != nil {
		return m.TrafficBackUrl
	}
	return ""
}

func (m *Stream) GetIsMyTarget() bool {
	if m != nil {
		return m.IsMyTarget
	}
	return false
}

func (m *Stream) GetSub1() string {
	if m != nil {
		return m.Sub1
	}
	return ""
}

func (m *Stream) GetSub2() string {
	if m != nil {
		return m.Sub2
	}
	return ""
}

func (m *Stream) GetSub3() string {
	if m != nil {
		return m.Sub3
	}
	return ""
}

func (m *Stream) GetSub4() string {
	if m != nil {
		return m.Sub4
	}
	return ""
}

func (m *Stream) GetSub5() string {
	if m != nil {
		return m.Sub5
	}
	return ""
}

func (m *Stream) GetGeoCode() []string {
	if m != nil {
		return m.GeoCode
	}
	return nil
}

func (m *Stream) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type StreamPageOptions struct {
	SubDomain            string   `protobuf:"bytes,1,opt,name=sub_domain,json=subDomain,proto3" json:"sub_domain,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	IsParking            bool     `protobuf:"varint,3,opt,name=is_parking,json=isParking,proto3" json:"is_parking,omitempty"`
	Templates            []int32  `protobuf:"varint,4,rep,packed,name=templates,proto3" json:"templates,omitempty"`
	Script               string   `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamPageOptions) Reset()         { *m = StreamPageOptions{} }
func (m *StreamPageOptions) String() string { return proto.CompactTextString(m) }
func (*StreamPageOptions) ProtoMessage()    {}
func (*StreamPageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{4}
}

func (m *StreamPageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamPageOptions.Unmarshal(m, b)
}
func (m *StreamPageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamPageOptions.Marshal(b, m, deterministic)
}
func (m *StreamPageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPageOptions.Merge(m, src)
}
func (m *StreamPageOptions) XXX_Size() int {
	return xxx_messageInfo_StreamPageOptions.Size(m)
}
func (m *StreamPageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPageOptions proto.InternalMessageInfo

func (m *StreamPageOptions) GetSubDomain() string {
	if m != nil {
		return m.SubDomain
	}
	return ""
}

func (m *StreamPageOptions) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *StreamPageOptions) GetIsParking() bool {
	if m != nil {
		return m.IsParking
	}
	return false
}

func (m *StreamPageOptions) GetTemplates() []int32 {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *StreamPageOptions) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type GetStreamRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamRequest) Reset()         { *m = GetStreamRequest{} }
func (m *GetStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetStreamRequest) ProtoMessage()    {}
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d357462b1646d3, []int{5}
}

func (m *GetStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamRequest.Unmarshal(m, b)
}
func (m *GetStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamRequest.Marshal(b, m, deterministic)
}
func (m *GetStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamRequest.Merge(m, src)
}
func (m *GetStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetStreamRequest.Size(m)
}
func (m *GetStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamRequest proto.InternalMessageInfo

func (m *GetStreamRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterEnum("page_api.LayoutType", LayoutType_name, LayoutType_value)
	proto.RegisterType((*Template)(nil), "page_api.Template")
	proto.RegisterType((*ListTemplatesRequest)(nil), "page_api.ListTemplatesRequest")
	proto.RegisterType((*ListTemplatesResponse)(nil), "page_api.ListTemplatesResponse")
	proto.RegisterType((*Stream)(nil), "page_api.Stream")
	proto.RegisterType((*StreamPageOptions)(nil), "page_api.StreamPageOptions")
	proto.RegisterType((*GetStreamRequest)(nil), "page_api.GetStreamRequest")
}

func init() { proto.RegisterFile("page_api.proto", fileDescriptor_41d357462b1646d3) }

var fileDescriptor_41d357462b1646d3 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x8e, 0xfc, 0x2b, 0x1d, 0xff, 0x44, 0x21, 0xb2, 0x8d, 0x73, 0xb6, 0xc4, 0xd3, 0x80, 0xc1,
	0xd8, 0x45, 0xb0, 0x39, 0xc9, 0xd5, 0x80, 0x01, 0x4b, 0x02, 0x0c, 0x19, 0x32, 0x34, 0x50, 0xd3,
	0x6b, 0x81, 0x96, 0x68, 0x97, 0xb5, 0x24, 0xaa, 0x22, 0x15, 0xc0, 0xaf, 0xd2, 0x9b, 0x3e, 0x40,
	0x5f, 0xa1, 0xb7, 0x7d, 0xaf, 0x82, 0x14, 0x25, 0x39, 0x4e, 0x8a, 0xdc, 0xf1, 0xfb, 0x78, 0xce,
	0x11, 0xcf, 0xc7, 0xef, 0x50, 0x30, 0xce, 0xc8, 0x8a, 0x06, 0x24, 0x63, 0xa7, 0x59, 0xce, 0x25,
	0x47, 0x76, 0x85, 0xbd, 0x4f, 0x2d, 0xb0, 0xef, 0x69, 0x92, 0xc5, 0x44, 0x52, 0x34, 0x86, 0x16,
	0x8b, 0xb0, 0x35, 0xb5, 0x66, 0x5d, 0xbf, 0xc5, 0x22, 0x84, 0xa0, 0x93, 0x92, 0x84, 0xe2, 0xd6,
	0xd4, 0x9a, 0x39, 0xbe, 0x5e, 0xa3, 0x1f, 0xc1, 0xe6, 0xcb, 0x25, 0xcd, 0x03, 0x16, 0xe1, 0xb6,
	0x8e, 0xec, 0x6b, 0x7c, 0xa3, 0xc3, 0xe5, 0x26, 0xa3, 0xb8, 0xa3, 0x69, 0xbd, 0x46, 0x27, 0x30,
	0x88, 0xc9, 0x86, 0x17, 0x32, 0xd0, 0x5b, 0x5d, 0xbd, 0x05, 0x25, 0x75, 0xaf, 0x02, 0x30, 0xf4,
	0x43, 0x9e, 0x4a, 0x9a, 0x4a, 0xdc, 0xd3, 0x9f, 0xa9, 0xa0, 0x2a, 0x57, 0x14, 0x2c, 0xc2, 0xfd,
	0xf2, 0xeb, 0x6a, 0x8d, 0xa6, 0x30, 0x64, 0x22, 0x48, 0x36, 0x81, 0x24, 0xf9, 0x8a, 0x4a, 0x6c,
	0x4f, 0xad, 0x99, 0xed, 0x03, 0x13, 0xff, 0x6f, 0xee, 0x35, 0x83, 0x7e, 0x85, 0x91, 0xcc, 0x49,
	0x2a, 0x98, 0xa4, 0x51, 0x50, 0xe4, 0x31, 0x76, 0x74, 0xfa, 0xb0, 0x26, 0xdf, 0xe4, 0x31, 0xfa,
	0x1e, 0x7a, 0x42, 0x12, 0x59, 0x08, 0x0c, 0xfa, 0x40, 0x06, 0xa1, 0x63, 0x80, 0x07, 0x26, 0xd8,
	0x82, 0xc5, 0x4c, 0x6e, 0xf0, 0xa0, 0x3c, 0x6c, 0xc3, 0x78, 0x9f, 0x2d, 0x38, 0xbc, 0x65, 0x42,
	0x56, 0x8a, 0x09, 0x9f, 0xbe, 0x2f, 0xa8, 0x90, 0xb5, 0x72, 0xed, 0x46, 0x39, 0xdd, 0x6f, 0x6b,
	0x4b, 0x8a, 0x4a, 0xcd, 0xf6, 0x96, 0x9a, 0x47, 0xe0, 0x54, 0x6a, 0x0a, 0xdc, 0xd1, 0xe9, 0xb6,
	0x91, 0x53, 0xa0, 0x5f, 0x60, 0x48, 0x96, 0x4b, 0x16, 0x33, 0x22, 0xa9, 0x92, 0xbb, 0x14, 0x6f,
	0x50, 0x73, 0x37, 0x11, 0x3a, 0x84, 0x6e, 0xcc, 0x12, 0x56, 0x6a, 0xd7, 0xf5, 0x4b, 0xa0, 0xda,
	0xe3, 0xcb, 0xa5, 0xa0, 0x52, 0x6b, 0xd7, 0xf5, 0x0d, 0xf2, 0xde, 0xc1, 0x77, 0x3b, 0xa7, 0x17,
	0x19, 0x4f, 0x05, 0x45, 0x7f, 0x80, 0x23, 0x2b, 0x52, 0x77, 0x31, 0x98, 0xa3, 0xd3, 0xda, 0x33,
	0x55, 0xbc, 0xdf, 0x04, 0xa9, 0x7b, 0x95, 0x5c, 0x92, 0x38, 0x08, 0x79, 0x91, 0x4a, 0xd3, 0x27,
	0x68, 0xea, 0x4a, 0x31, 0xde, 0x97, 0x0e, 0xf4, 0x5e, 0xcb, 0x9c, 0x92, 0xe4, 0x39, 0x5b, 0xd5,
	0xe2, 0x38, 0x46, 0x9c, 0x1f, 0xa0, 0x5f, 0x88, 0x6d, 0x57, 0xf5, 0x14, 0xbc, 0x89, 0x1e, 0xf9,
	0xad, 0xf3, 0xc4, 0x6f, 0x5a, 0xd0, 0xee, 0x96, 0xa0, 0x08, 0x3a, 0x21, 0x8f, 0xa8, 0xf1, 0x92,
	0x5e, 0xa3, 0xff, 0x00, 0x65, 0x39, 0x8d, 0x49, 0x1a, 0xb1, 0x74, 0x15, 0xf0, 0x4c, 0x32, 0x9e,
	0x0a, 0x2d, 0xcd, 0x60, 0x7e, 0xd4, 0xb4, 0x59, 0x9e, 0xf6, 0x8e, 0xac, 0xe8, 0xab, 0x32, 0xc4,
	0x3f, 0x68, 0xd2, 0x0c, 0x85, 0xae, 0x61, 0x7f, 0xb7, 0x90, 0xfd, 0x72, 0xa1, 0xf1, 0x4e, 0x95,
	0x4b, 0x18, 0xcb, 0xb7, 0x24, 0x5d, 0x8b, 0xba, 0x88, 0xf3, 0x72, 0x91, 0x51, 0x99, 0x52, 0xd5,
	0x98, 0x81, 0x2b, 0x73, 0xe5, 0x85, 0x30, 0x58, 0x90, 0x70, 0xad, 0xbd, 0x0e, 0xba, 0xeb, 0xb1,
	0xe1, 0x2f, 0x49, 0xb8, 0x56, 0x6e, 0xdf, 0x1d, 0x9a, 0xc1, 0x93, 0xa1, 0x41, 0xd0, 0x11, 0xc5,
	0xe2, 0x4f, 0x3c, 0x2c, 0x55, 0x53, 0x6b, 0xc3, 0xcd, 0xf1, 0xa8, 0xe6, 0xe6, 0x86, 0x3b, 0xc3,
	0xe3, 0x9a, 0x3b, 0x33, 0xdc, 0x39, 0xde, 0xaf, 0xb9, 0x73, 0xc3, 0x5d, 0x60, 0xb7, 0xe6, 0x2e,
	0xd4, 0x45, 0xae, 0x28, 0x0f, 0xf4, 0xed, 0x1c, 0x4c, 0xdb, 0x6a, 0xd2, 0x57, 0x94, 0x5f, 0xa9,
	0x0b, 0x9a, 0x80, 0x1d, 0x16, 0x79, 0x4e, 0xd3, 0x70, 0x83, 0x91, 0x4e, 0xa9, 0xb1, 0xf7, 0xd1,
	0x82, 0x83, 0x27, 0x5a, 0xa0, 0x9f, 0x01, 0x44, 0xb1, 0x08, 0x22, 0x9e, 0x10, 0x96, 0x6a, 0x6b,
	0x39, 0xbe, 0x23, 0x8a, 0xc5, 0xb5, 0x26, 0xd4, 0x00, 0x98, 0xad, 0xd2, 0x63, 0x06, 0xa9, 0x34,
	0x26, 0x82, 0x8c, 0xe4, 0x6b, 0x96, 0xae, 0xb4, 0xd1, 0x6c, 0xdf, 0x61, 0xe2, 0xae, 0x24, 0xd0,
	0x4f, 0xdb, 0x63, 0x50, 0x4e, 0xe3, 0x96, 0xe5, 0xd5, 0xa3, 0x11, 0xe6, 0x2c, 0x93, 0xc6, 0x70,
	0x06, 0x79, 0xbf, 0x81, 0xfb, 0x2f, 0x95, 0xe5, 0x19, 0xab, 0xf7, 0xa0, 0xb2, 0xa1, 0xd5, 0xd8,
	0xf0, 0xf7, 0xbf, 0x01, 0x6e, 0x9b, 0x77, 0xcf, 0x81, 0x2e, 0x4d, 0x32, 0xb9, 0x71, 0xf7, 0xd0,
	0x00, 0xfa, 0x11, 0x15, 0x6b, 0xc9, 0x33, 0xd7, 0x42, 0x00, 0xbd, 0x84, 0x2f, 0x58, 0x4c, 0xdd,
	0x16, 0x1a, 0x82, 0x4d, 0x22, 0x92, 0x49, 0xf6, 0x40, 0xdd, 0xf6, 0xfc, 0x83, 0x05, 0x7d, 0xa5,
	0xc1, 0x3f, 0x19, 0x43, 0x3e, 0x8c, 0x1e, 0x4d, 0x32, 0x3a, 0x6e, 0x9c, 0xf3, 0xdc, 0x03, 0x35,
	0x39, 0xf9, 0xe6, 0x7e, 0xf9, 0x04, 0x78, 0x7b, 0xe8, 0x2f, 0x70, 0xea, 0x3e, 0xd0, 0xa4, 0x89,
	0xdf, 0x6d, 0x6e, 0xe2, 0xee, 0xba, 0xd4, 0xdb, 0x5b, 0xf4, 0xf4, 0x8f, 0xe5, 0xec, 0x6b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x03, 0xb1, 0xf7, 0x40, 0x6a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PageApiClient is the client API for PageApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PageApiClient interface {
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*Stream, error)
}

type pageApiClient struct {
	cc *grpc.ClientConn
}

func NewPageApiClient(cc *grpc.ClientConn) PageApiClient {
	return &pageApiClient{cc}
}

func (c *pageApiClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, "/page_api.PageApi/ListTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageApiClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*Stream, error) {
	out := new(Stream)
	err := c.cc.Invoke(ctx, "/page_api.PageApi/GetStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageApiServer is the server API for PageApi service.
type PageApiServer interface {
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	GetStream(context.Context, *GetStreamRequest) (*Stream, error)
}

func RegisterPageApiServer(s *grpc.Server, srv PageApiServer) {
	s.RegisterService(&_PageApi_serviceDesc, srv)
}

func _PageApi_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageApiServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/page_api.PageApi/ListTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageApiServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageApi_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageApiServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/page_api.PageApi/GetStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageApiServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PageApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "page_api.PageApi",
	HandlerType: (*PageApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTemplates",
			Handler:    _PageApi_ListTemplates_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _PageApi_GetStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "page_api.proto",
}
